name: my_explore_together
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.8.0
  image_picker: ^1.1.2
  fl_chart: ^0.69.2
  pinput: ^5.0.0
  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  cloudinary_public: ^0.23.1
  lottie: ^3.2.0
  cached_network_image: ^3.4.0
  cupertino_icons: ^1.0.8
  string_similarity: ^2.1.1
  connectivity_plus: ^6.1.1
  provider: ^6.1.2
  flutter_gemini: ^3.0.0
  http: ^1.2.2
  shared_preferences: ^2.3.4
  intl: ^0.20.1
  rxdart: ^0.28.0
  flutter_native_splash: ^2.4.4
  onesignal_flutter: ^5.2.8
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/system/animation/loading/
    - assets/system/animation/greet/
    - assets/system/bg/
    - assets/system/iconImage/
    - assets/system/splash/

flutter_native_splash:
  color: "#2196F3"
  image: assets/system/splash/splash.png
  branding: assets/system/splash/brand.png
  android_12:
    image: assets/system/splash/splash.png
    color: "#2196F3"
    branding: assets/system/splash/brand.png